// const authRouter = require("./authRoute")
const authRouter = require('./authRoute')
const brandRouter = require('./brandRoute')
const categoryRouter = require('./categoryRoute')
const userRouter = require('./userRoute')
const specificationRouter = require('./specificationRoute')
const productRouter = require('./productRoute')
const colorRouter = require('./colorRoute')
const memoryRouter = require('./memoryRoute')
const productVariantRouter = require('./productVariantRoute')
const cartRouter = require('./cartRoute')
const orderRouter = require('./orderRoute')
const paymentRouter = require('./paymentRoute')
const reviewRouter = require('./reviewRoute')
const commentRouter = require('./commentRoute')
const storeBranchRouter = require('./storeBranchRoute')
const discountRouter = require('./discountRoute')
const voucherRouter = require('./voucherRoute')
const inventoryRouter = require('./inventoryRoute')
const adminRouter = require('./adminRoute')
// const shippingRouter = require('./shippingRoute')
// const vnpayRouter = require('./vnpayRoute')
// const cartRouter = require('./cart.router')
// const brandRouter = require('./brand.router')
// const orderRouter = require('./order.router')


const initRoutes = (app) => {
    app.use("/api/auth", authRouter)
    app.use("/api/brand", brandRouter)
    app.use("/api/category", categoryRouter)
    app.use("/api/user", userRouter)
    app.use("/api/specification", specificationRouter)
    app.use("/api/product", productRouter)
    app.use("/api/color", colorRouter)
    app.use("/api/memory", memoryRouter)
    app.use("/api/productVariant", productVariantRouter)
    app.use("/api/carts", cartRouter)
    app.use("/api/orders", orderRouter)
    app.use("/api/payment", paymentRouter)
    app.use("/api/review", reviewRouter)
    app.use("/api/comment", commentRouter)
    app.use("/api/storeBranch", storeBranchRouter)
    app.use("/api/discount", discountRouter)
    app.use("/api/voucher", voucherRouter)
    app.use("/api/inventory", inventoryRouter)
    app.use("/api/admins", adminRouter)
    // app.use("/api/shipping", shippingRouter)
    // app.use("/api/vnpay", vnpayRouter)
    // app.use("/api/user", userRouter)
    // app.use("/api/carts", cartRouter)
    // app.use("/api/brand", brandRouter)
    // app.use("/api/orders", orderRouter)
    // app.use("/api", authRouter)
    // app.use("/", authRouter)
}

module.exports = initRoutes;